export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const LOAD_INGREDIENTS = "LOAD_INGREDIENTS";
export const ERROR_LOADING_INGREDIENTS = "ERROR_LOADING_INGREDIENTS";

export const LOAD_ORDERS_STARTED = "LOAD_ORDERS_STARTED";
export const LOAD_ORDERS_SUCCESS = "LOAD_ORDERS_SUCCESS";
export const LOAD_ORDERS_FAILED = "LOAD_ORDERS_FAILED";

export const PURCHASE_PROCESS_INIT = "PURCHASE_PROCESS_INIT";
export const PURCHASE_BURGUER_STARTED = "PURCHASE_BURGUER_STARTED";
export const PURCHASE_BURGUER_SUCCESS = "PURCHASE_BURGUER_SUCCESS";
export const PURCHASE_BURGUER_FAILURE = "PURCHASE_BURGUER_FAILURE";

export const AUTH_STARTED = "AUTH_STARTED";
export const AUTH_USER = "AUTH_USER";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAILED = "AUTH_FAILED";
export const AUTH_UNAUTHENTICATE = "AUTH_UNAUTHENTICATE";
export const AUTH_INIT_UNAUTHENTICATE = "AUTH_INIT_UNAUTHENTICATE";
export const AUTH_CHECK_TIMEOUT = "AUTH_CHECK_TIMEOUT";
export const CHECK_AUTH_STATUS = "CHECK_AUTH_STATUS";
