export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const LOAD_INGREDIENTS = "LOAD_INGREDIENTS";
export const ERROR_LOADING_INGREDIENTS = "ERROR_LOADING_INGREDIENTS";

export const LOAD_ORDERS = "LOAD_ORDERS";
export const PURCHASE_BURGUER_STARTED = "PURCHASE_BURGUER_START";
export const PURCHASE_BURGUER_SUCCESS = "PURCHASE_BURGUER_SUCCESS";
export const PURCHASE_BURGUER_FAILURE = "PURCHASE_BURGUER_FAILURE";
